### ISSUE TITLE
none expression not working

### ISSUE THREAD

**Issue by Tangnaran** [0xbs/premade-applicants-filter#12]
hey, man! loving the addon so far, long time PGF user but still new to the applicants one.

just noticed the `none` expression doesn't seem to be working, can only achieve the desired result through `not all`.

![image](https://github.com/0xbs/premade-applicants-filter/assets/55262207/830efa83-34fe-4d31-a3fc-2a2431af11ef)

![image](https://github.com/0xbs/premade-applicants-filter/assets/55262207/1d6fb1eb-133b-4e18-be49-d88347fc06ea)

i get a semantic error everytime i try the expression above with the `none` expression.

ty

**Comment by 0xbs** [comment]
Thanks for the report, there is indeed a problem with `none`, `exists` and `every` because of a wrong variable name: it should be `applicantEnv` instead of `env`.

Also there is another bug in the README. `none` is the same as `not some` and not `not all`.

For now, you may work around the issue by using only `some` and `all` and `not`.

**Comment by 0xbs** [comment]
Fixed, new version will be released shortly.
