### ISSUE TITLE
Semantic error when using classes

### ISSUE THREAD

**Issue by RavenDT** [0xbs/premade-applicants-filter#6]
The following expression throws a semantic error:

![image](https://user-images.githubusercontent.com/5491569/132793681-5d09eade-cb69-4010-9e12-2dbbf0f95c66.png)

This, of course, could be user error, but I double-checked the criteria on the wiki, and I am not sure why it's not working.

**Comment by 0xbs** [comment]
There is a plural s missing on both `warlocks` and `deathknights`. Additionally, both are numbers, so you have to compare them, e.g. `warlocks > 0 or deathknights > 0`. It's all in the documentation, if it says different somewhere, please post a link.

**Comment by RavenDT** [comment]
On the frint page of the repo, README.md:

![image](https://user-images.githubusercontent.com/5491569/132868395-4894af0b-6627-453e-9726-5ccd6772e2bf.png)

**Comment by 0xbs** [comment]
I think you are mixing up Premade **Groups** Filter and Premade **Applicants** Filter. The keywords in your screenshot only apply for the second addon filtering applicants of groups.

**Comment by RavenDT** [comment]
Then I guess the documentation is backwards.

The first screenshot shows I was using the singular boolean option in Premade Applicants Filter in the game, because we were filtering applicants to our raid.

The second screenshot was taken from the README.md in this repository.

https://github.com/0xbs/premade-applicants-filter/commit/dd90d9e73677882dcb22f30ac54642089d25570c

The corresponding section in the Premade Groups Filter shows the plurals as integers:

https://github.com/0xbs/premade-groups-filter/wiki/Keywords#members

**Comment by 0xbs** [comment]
Ah sorry you are in fact using the applicant filter! Sorry for the confusion on my side.

Then the issue is clear: your expression is not quantified. This means you will have to wrap your expression in an _all_ or _some_ expression. The reason for this is that all applicants are technically an applicant group that consists of a list of members. Most of the time, there is only one member in this group.

In other words: this means you will always have to make a statement about the group, not about a single member, even if there is only one applicant.

So instead of saying the applicant has to be either a warlock or deathknight, you have say "all members of the applicant group are either a warlock or a deathknight" which translates to `all("warlock or deathknight")`

Or you might want to say "at least one (some) member of the applicant group is a warlock or deathknight and the rest can be any class. In this case the correct expression is `some("warlock or deathknight")`

**Comment by RavenDT** [comment]
Ahh, that makes more sense!  Thank you for the clarification!
